
DROP TABLE IF EXISTS user ;
DROP TABLE IF EXISTS picture;
DROP TABLE IF EXISTS designer;


CREATE TABLE user (

    id INTEGER  PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    profile_picture TEXT DEFAULT "0.png"

);


CREATE TABLE picture (

    id INTEGER PRIMARY KEY AUTOINCREMENT,
    owner_id INTEGER NOT NULL,
    picture_name TEXT  UNIQUE NOT NULL,
    published TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES user (id)

);
